### ISSUE TITLE
Supply a name for the Instrumented client?

### ISSUE THREAD

**Issue by esiqveland** [raskasa/metrics-okhttp#22]
If you have more than one client in a project (different services with different expected SLAs and demands), it would be useful to give each instrumented client an identifiable name.

You also don't want to in general share threadpools with clients between different services you consume.

**Comment by raskasa** [comment]
I don't have any strong opinions against this.

How would the API look?  Outline how you're envisioning this addition.  Or feel free to submit a pull request!
