### ISSUE TITLE
Upgrade to OkHttp 3.x

### ISSUE THREAD

**Issue by raskasa** [raskasa/metrics-okhttp#36]

**Comment by tburch** [comment]
👍

**Comment by ben-manes** [comment]
This just required changing the imports, so easy to fork for internal use. The custom `InstrumentedExecutorService` can be dropped to use the version supplied by metrics-core.

**Comment by raskasa** [comment]
First pass started in #38.  Incomplete, but enough to get started.  Still working on a few other open issues (i.e. #49, etc.).
