### ISSUE TITLE
Release for okhttp3

### ISSUE THREAD

**Issue by stannnous** [raskasa/metrics-okhttp#51]
I've seen the library has been updated for okhttp3, any chance we can get a 0.3.0 release?

**Comment by raskasa** [comment]
Haven't had the opportunity to test the latest changes as thoroughly as I've wanted.

One specific case is ensuring correct instrumentation when a new instance is created via `OkHttpClient.newBuilder()`.

Will looking to do so in the next couple of weeks when things at work settle down.

I'd be happy to accept any contributions of unit tests around the above mentioned use case.

**Comment by mwiede** [comment]
@stannnous why not creating a PR so that okhttp3 becomes available? ;-)

**Comment by stannnous** [comment]
Not sure if this is what you had in mind: https://github.com/raskasa/metrics-okhttp/pull/52

We've also been running a forked release without issue.

**Comment by raskasa** [comment]
Extreme delay here.  I've released 0.4.0 (0.3.0 was a bad release).  Looking to get back into actively maintaining as I have an opportunity to use it at work now.
